server:
  enabled: true

image:
  repository: rabbitmq
  tag: "3-alpine"
  pullPolicy: IfNotPresent


# resources: {}
resources:
  limits:
    memory: "300Mi"
    cpu: "500m"
  requests:
    memory: "200Mi"
    cpu: "100m"