{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    icom.symbiote.service: symbiote-mongo
  name: symbiote-mongo
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    icom.symbiote.service: symbiote-mongo
{{- end -}}