{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    icom.symbiote.service: symbiote-mongo
  name: {{ .Release.Name }}-symbiote-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      icom.symbiote.service: symbiote-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        icom.symbiote.service: symbiote-mongo
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: symbiote-mongo
          ports:
            - containerPort: 27017
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - mountPath: /data/db
              name: symbiote-core-vol
      volumes:
        - name: symbiote-core-vol
          persistentVolumeClaim:
            claimName: symbiote-core-vol
{{- end -}}