{{- if .Values.server.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    icom.symbiote.service: symbiote-core-vol
  name: symbiote-core-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
{{- end -}}