{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    icom.symbiote.service: symbiote-aam
  name: symbiote-aam
spec:
  ports:
    - name: "8443"
      port: 8443
      targetPort: 8443
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    icom.symbiote.service: symbiote-aam
{{- end }}