{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    icom.symbiote.service: symbiote-admin
  name: {{ .Release.Name }}-symbiote-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      icom.symbiote.service: symbiote-admin
  template:
    metadata:
      labels:
        icom.symbiote.service: symbiote-admin
    spec:
      containers:
        - name: symbiote-admin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: symbioteh2020/symbiote-admin:3.1.6
          command: ["/bin/sh","-c"]

          args: ["java -Xmx1024m -Duser.home=/home -Dspring.output.ansi.enabled=NEVER -jar $(ls *.jar)"]

          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - mountPath: /home/bootstrap.properties
              name: bootstrap-properties-configmap-volume
              subPath: bootstrap.properties
          ports:
          - containerPort: 8250
      volumes:
        - name: bootstrap-properties-configmap-volume
          configMap:
              name: bootstrap-properties-configmap
{{- end}}