{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    icom.symbiote.service: symbiote-coreinterface
  name: symbiote-coreinterface
spec:
  selector:
    icom.symbiote.service: symbiote-coreinterface
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
{{- end }}