{{- if and .Values.server.enabled .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: symbiote-coreinterface-ingress
 annotations:
   kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
   nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
 tls:
 - hosts:
   - {{ .Values.ingress.host }}
   secretName: {{ .Values.ingress.tls.secretName }}
 rules:
 - host: {{ .Values.ingress.host }}
   http:
     paths:
     - path: {{ .Values.ingress.path }}
       pathType: Prefix
       backend:
         service:
           name: symbiote-coreinterface
           port:
             number: 8100
{{- end }}