server:
  enabled: true

image:
  repository: symbioteh2020/symbiote-aam
  tag: "5.0.12"
  pullPolicy: IfNotPresent


# resources: {}
resources: 
  limits:
    memory: "1000Mi"
    cpu: "1"
  requests:
    memory: "500Mi"
    cpu: "500m"