server:
  enabled: true

image:
  repository: symbioteh2020/symbiote-admin
  tag: "3.1.6"
  pullPolicy: IfNotPresent


# resources: {}
resources:
  limits:
    memory: "700M"
    cpu: "1"
  requests:
    memory: "300M"
    cpu: "500m"

ingress:
  enabled: true

  ingressClassName: nginx

  host: core-test.iotfeds.intracom-telecom.com

  path: /administration

  tls: 
    secretName: wildcard-ingress-tls