{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    icom.symbiote.service: symbiote-rabbitmq
  name: symbiote-rabbitmq
spec:
  ports:
    - name: "5671"
      port: 5671
      targetPort: 5671
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    icom.symbiote.service: symbiote-rabbitmq
{{- end -}}